import sys
import subprocess

AUTOGENERATED_CLIENT_FILE = "pygls/lsp/_base_client.py"
AUTOGENERATED_SERVER_FILE = "pygls/lsp/_base_server.py"

subprocess.run(["poe", "generate_code"])

result = subprocess.run(
    [
        "git",
        "diff",
        "--exit-code",
        AUTOGENERATED_CLIENT_FILE,
        AUTOGENERATED_SERVER_FILE,
    ],
    stdout=subprocess.DEVNULL,
)

if result.returncode == 0:
    print("✅ Pygls client and server are up to date")
else:
    print(
        (
            "🔴 Pygls client or server not up to date\n"
            "1. Re-generate with: `uv run poe generate_code`\n"
            "2. Commit"
        )
    )
    sys.exit(result.returncode)
