name: Release Pygls to PyPI

on:
  release:
    types: [published]

jobs:
  relase:
    name: "🚀 Release 🚢"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ssh-key: ${{secrets.CI_RELEASE_DEPLOY_KEY}}
          fetch-depth: 0
      - name: Use Python "3.10"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.7.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Generate the latest changelog
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: git-cliff-changes.tmp.md
      - name: Update the changelog
        run: |
          git checkout main
          cat git-cliff-changes.tmp.md | sed -i "3r /dev/stdin" CHANGELOG.md
          git config --global user.name 'Github Action'
          git config --global user.email 'github.action@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md"
          git push
      - name: Update CONTRIBUTORS.md
        run: |
          git checkout main
          uv run poe generate_contributors_md
          if [[ $(git diff --stat CONTRIBUTORS.md) != '' ]]; then
            git add CONTRIBUTORS.md
            git commit -m "chore: update CONTRIBUTORS.md"
            git push
          fi
      - name: Release
        run: |
          uv build
          uvx poetry publish --username "__token__" --password ${{ secrets.PYPI_API_TOKEN }}
