name: Release Pygls to PyPI

on:
  release:
    types: [published]

jobs:
  relase:
    name: "🚀 Release 🚢"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ssh-key: ${{secrets.CI_RELEASE_DEPLOY_KEY}}
          fetch-depth: 0
      - name: Use Python "3.10"
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          version: "0.7.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Generate the latest changelog
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # v4.4.2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: git-cliff-changes.tmp.md
      - name: Update the changelog
        run: |
          git checkout main
          cat git-cliff-changes.tmp.md | sed -i "3r /dev/stdin" CHANGELOG.md
          git config --global user.name 'Github Action'
          git config --global user.email 'github.action@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md"
          git push
      - name: Update CONTRIBUTORS.md
        run: |
          git checkout main
          uv run poe generate_contributors_md
          if [[ $(git diff --stat CONTRIBUTORS.md) != '' ]]; then
            git add CONTRIBUTORS.md
            git commit -m "chore: update CONTRIBUTORS.md"
            git push
          fi
      - name: Release
        run: |
          uv build
          uvx poetry publish --username "__token__" --password ${{ secrets.PYPI_API_TOKEN }}
